### ISSUE TITLE
Apps Failing to Import Issue

### ISSUE THREAD

**Issue by sukoshiotokonoko** [Flow-Works/FlowOS-OLD#112]
Sometimes, when I reload the page, this error appears:

unable to import data:text/javascript;base64,ZXhwb3J0IGRlZmF1bHQgY2xhc3MgMXYxLmxvbCB7CiAgbWV0YSA9IHsKICAgIG5hbWU6ICcxdjEubG9sJywKICAgIGRlc2NyaXB0aW9uOiAnRGlzY292ZXIgMXYxLCB0aGUgb25saW5lIGJ1aWxkaW5nIHNpbXVsYXRvciAmIHRoaXJkIHBlcnNvbiBzaG9vdGluZyBnYW1lLiBCYXR0bGUgcm95YWxlLCBidWlsZCBmaWdodCwgYm94IGZpZ2h0LCB6b25lIHdhcnMgYW5kIG1vcmUgZ2FtZSBtb2RlcyB0byBlbmpveSEnLAogICAgaWNvbjogJ2h0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9DcmVlcGVyR2F0ZS9jdXN0b20tZmxvd29zLXJlc3Bvc2l0b3J5L21haW4vYXNzZXRzLzF2MWxvbGljb24ud2VicCcsCiAgICBwa2c6ICcxdjEubG9sJywKICAgIHZlcnNpb246ICcxLjAuMCcKICB9CgogIGFzeW5jIG9wZW4gKCkgewogICAgY29uc3Qgd2luID0gd2luZG93LndtLmNyZWF0ZVdpbmRvdyh7CiAgICAgIHRpdGxlOiB0aGlzLm1ldGEubmFtZSwKICAgICAgaWNvbjogdGhpcy5tZXRhLmljb24sCiAgICAgIHdpZHRoOiA3MDAsCiAgICAgIGhlaWdodDogNTAwCiAgICB9KQoKICAgIGNvbnN0IHhvciA9IHsKICAgICAgcmFuZG9tTWF4OiAxMDAsCiAgICAgIHJhbmRvbU1pbjogLTEwMCwKCiAgICAgIGVuY29kZTogKHN0cikgPT4gewogICAgICAgIGlmICghc3RyKSByZXR1cm4gc3RyCiAgICAgICAgcmV0dXJuIGVuY29kZVVSSUNvbXBvbmVudCgKICAgICAgICAgIHN0cgogICAgICAgICAgICAudG9TdHJpbmcoKQogICAgICAgICAgICAuc3BsaXQoJycpCiAgICAgICAgICAgIC5tYXAoKGNoYXIsIGluZCkgPT4KICAgICAgICAgICAgICBpbmQgJSAyID8gU3RyaW5nLmZyb21DaGFyQ29kZShjaGFyLmNoYXJDb2RlQXQoKSBeIDIpIDogY2hhcgogICAgICAgICAgICApCiAgICAgICAgICAgIC5qb2luKCcnKQogICAgICAgICkKICAgICAgfSwKICAgICAgZGVjb2RlOiAoc3RyKSA9PiB7CiAgICAgICAgaWYgKCFzdHIpIHJldHVybiBzdHIKICAgICAgICBjb25zdCBbaW5wdXQsIC4uLnNlYXJjaF0gPSBzdHIuc3BsaXQoJz8nKQoKICAgICAgICByZXR1cm4gKAogICAgICAgICAgZGVjb2RlVVJJQ29tcG9uZW50KGlucHV0KQogICAgICAgICAgICAuc3BsaXQoJycpCiAgICAgICAgICAgIC5tYXAoKGNoYXIsIGluZCkgPT4KICAgICAgICAgICAgICBpbmQgJSAyID8gU3RyaW5nLmZyb21DaGFyQ29kZShjaGFyLmNoYXJDb2RlQXQoMCkgXiAyKSA6IGNoYXIKICAgICAgICAgICAgKQogICAgICAgICAgICAuam9pbignJykgKyAoc2VhcmNoLmxlbmd0aCA/ICc/JyArIHNlYXJjaC5qb2luKCc/JykgOiAnJykKICAgICAgICApCiAgICAgIH0KICAgIH0KCiAgICB3aW4uY29udGVudC5zdHlsZS5iYWNrZ3JvdW5kID0gJ3ZhcigtLWJhc2UpJwogICAgd2luLmNvbnRlbnQuaW5uZXJIVE1MID0gYAogICAgICA8aWZyYW1lIHNyYz0iL3NlcnZpY2UvJHt4b3IuZW5jb2RlKCdodHRwczovMXYxLmxvbC8nKX0iIHN0eWxlPSJ3aWR0aDogMTAwJTtoZWlnaHQ6IDEwMCU7Ym9yZGVyOiBub25lOyIvPgogICAgYAoKICAgIHJldHVybiB3aW4KICB9Cn0=
SyntaxError: Invalid or unexpected token

Afterwards, any external apps don't work anymore, whether I made them in the Applications folder or they are from the official repository.

**Comment by ghost** [comment]
It seems as though you made a broken 1v1.lol application.

**Comment by ghost** [comment]
The problem is at line 1: class names cannot have dots in them.
