### ISSUE TITLE
Switch UV to version 1.0.11

### ISSUE THREAD

**Issue by ghost** [Flow-Works/FlowOS-OLD#168]
**Is your feature request related to a problem? Please describe.**
This feature request should fix all the `RangeError` errors, and possible clear up issues with the `TypeError: failed to fetch` error

**Describe the solution you'd like**
Switch UV version to 1.0.11

**Describe alternatives you've considered**
I've considered a proxy switcher in settings like in the legacy version of FlowOS.

**Comment by JeromeIsInvesting** [comment]
This is terrible, the Range Errors make this website great, why are you trying to fix them?

**Comment by JeromeIsInvesting** [comment]
"ThinLiquid" you do not know the slightest of how to improve this website. If you do not add gambling I will have to share my ideas with another creator, Cusworth21.  Please respond ThinLiquid if you want to keep this idea.

Thank You.
