### ISSUE TITLE
Site is constantly down 

### ISSUE THREAD

**Issue by zcraftelite9495** [Flow-Works/FlowOS-OLD#56]
The website (https://flow-os.me) is constantly down, with no explanation. Is this supposed to be happening?

[EDIT] I wasnt too clear in this, but often the site will go down with a 521 "Web Server is Down" error. This is on and off but as of now it has been in this state since 12:35 PM EST on November 16th 2023 to November 7th 2023 (NOW)

**Comment by ghost** [comment]
This issue will be closed as it is not a problem with the source code, instead contact @proudparrot2 on Discord.
