### ISSUE TITLE
File management improvements

### ISSUE THREAD

**Issue by Xanderplayz18** [Flow-Works/FlowOS-OLD#91]
**Is your feature request related to a problem? Please describe.**
I hate that I cannot copy/rename/delete files

**Describe the solution you'd like**
If you right click on a file, a context menu appears where you can copy/rename/delete the file

**Describe alternatives you've considered**
Maybe selecting the file then clicking a 3 dots menu?

**Additional context**

**Comment by ghost** [comment]
sounds good to me.
